# Generated by Django 3.1.14 on 2021-12-23 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0012_auto_20211010_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotator',
            field=models.ForeignKey(help_text='User ID of the annotator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='reviewer',
            field=models.ForeignKey(help_text='User ID of the reviewer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='status',
            field=models.CharField(choices=[('review', 'In Review'), ('done', 'Done')], default='review', max_length=6),
        ),
    ]
