# Generated by Django 3.1.14 on 2021-12-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20211010_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('AN', 'Annotator'), ('RV', 'Reviewer')], default='AN', max_length=2),
        ),
    ]
